# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Upgrade the Xcode project to Xcode 8"
  lane :upgrade_xcode_project do
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    xcodeprojpath = "platforms/ios/MyApp.xcodeproj"

    upgrade_super_old_xcode_project(
      path: xcodeprojpath,
      team_id: team_id
    )
  end

  desc "Build Debug"
  lane :build_debug do
    ionic(
      platform: 'ios',
      release: false,
      type: 'development'
    )
  end

  desc "Build Debug Prod"
  lane :build_debug_prod do
    ionic(
      platform: 'ios',
      release: false,
      prod: true,
      type: 'development'
    )
  end

  desc "Build Release"
  lane :build_release do
    ionic(
      platform: 'ios',
      release: true,
      prod: true
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do
  desc "Build Debug"
  lane :build_debug do
    ionic(
      platform: 'android',
      release: false
    )
  end

  desc "Build Debug Prod"
  lane :build_debug_prod do
    ionic(
      platform: 'android',
      release: false,
      prod: true
    )
  end

  desc "Build Release"
  lane :build_release do
    ionic(
      platform: 'android',
      release: true,
      prod: true,

      keystore_path: '../Dropbox/zaehlerstand.keystore',
      keystore_alias: 'Zaehlerstand',
      keystore_password: '168597',
      key_password: '168597'
    )
  end
end
